### ISSUE TITLE
Release version 1.0.0

### ISSUE THREAD

**Issue by samwilson** [JakubOnderka/PHP-Console-Highlighter#14]
What blockers are there to releasing a 1.0.0 version? It seems that this package is already used in production (albeit continuous-integration production, rather than user-facing).

**Comment by nunomaduro** [comment]
@JakubOnderka Can you tag a stable version? 👍

**Comment by JakubOnderka** [comment]
Hi. I released v0.4 version, so enjoy!

**Comment by samwilson** [comment]
Why not declare it stable and leap to 1.0.0? :-)

**Comment by nunomaduro** [comment]
@JakubOnderka Yeah. Technically 0.4 is not a stable version.

**Comment by JakubOnderka** [comment]
You are right, guys:

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0. – https://semver.org/spec/v1.0.0.html#how-do-i-know-when-to-release-100 

So next release will be 1.0.0
